version: '3'

services:
  db:
    image: mariadb:10.7
    container_name: gorestdb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: goroot
      MYSQL_DATABASE: gorest
    ports:
      - "3307:3306"
    volumes:
      - "./resources/db/:/docker-entrypoint-initdb.d/:ro"